config/routes.rb
RailsApp::Application.routes.draw do

  match 'translations' => 'translations#index'
  match 'translations/total/:language(/:duration)' => 'translations#total'
  match 'translations/language/:language' => 'translations#language'
  match 'translations/translator_history/:language/:ted_id' => 'translations#translator_history' 
  match 'translations/translator/:language/:ted_id' => 'translations#translator', :as => :view_translator 

end

app/models/daily_extract.rb
class DailyExtract < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/daily_extracts.rb
class DailyExtracts < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessor :firstScrapeDate
  attr_accessible :firstScrapeDate

  attr_accessor :lastActiveDate
  attr_accessible :lastActiveDate
end

app/models/last_translator.rb
class LastTranslator < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	respond_to :json

	def index
	end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
	respond_to :html, :only => [:index, :language, :translator]
	respond_to :json, :only => [:total, :translator_history]

	def index
		
	end

	def language
		@totalTranslators = DailyExtracts.select("count(ted_id) as translators").where("for_language = ?", params[:language]).group("for_date").order("for_date ASC").last
		@totalTasksCompleted = DailyExtracts.select("sum(translations) as tasks").where("for_language = ?", params[:language]).group("for_date").order("for_date ASC").last
		@translators = DailyExtracts.select("ted_id, profile_url, name, translations, location").where("for_language = ?", params[:language]).where(:for_date => DailyExtracts.select("MAX(for_date)")).order("translations DESC")

		@newTranslators = 0
		@activeTranslators = 0

		@translators.each do |translator|

			translator.firstScrapeDate = DailyExtracts.select("for_date").where("for_language = ?", params[:language]).where(:ted_id => translator.ted_id).order("for_date ASC").limit(1).first.for_date

			if (Date.today - translator.firstScrapeDate).to_i < 14 then
				@newTranslators += 1
			end

			previousForDate = DailyExtracts.select("for_date").where("for_language = ?", params[:language]).where(:ted_id => translator.ted_id).where("translations != ?", translator.translations).order("for_date DESC").limit(1).first
			
			if previousForDate then

				translator.lastActiveDate = previousForDate.for_date

				if (Date.today - translator.lastActiveDate).to_i < 14 then
					@activeTranslators += 1
				end

			else
				translator.lastActiveDate = translator.firstScrapeDate
			end

		end

		@newCompletedTasks = DailyExtracts.select("SUM(translations) as translations").where("for_language = ?", params[:language]).group("for_date").order('for_date DESC').limit(1).first.translations - DailyExtracts.select("translations").where("for_language = ?", params[:language]).where("for_date = ?", Date.today - 14).sum("translations")
	end

	def total

		if params[:duration] != nil
			records = DailyExtracts.select("for_language, for_date, sum(translations) as translations").where("for_language = ?", params[:language]).where(:for_date => (Time.now.months_ago(params[:duration].to_i).to_date..Time.now.to_date)).group("for_date")
		else
			records = DailyExtracts.select("for_language, for_date, sum(translations) as translations").where("for_language = ?", params[:language]).group("for_date")
		end

		respond_with records

	end

	def translator_history
		respond_with DailyExtracts.select("ted_id, profile_url, name, photo_url, location, profile_languages, for_language, translations, for_date").where(:ted_id => params[:ted_id]).where(:for_language => params[:language]).order("for_date ASC")
	end

	def translator
		@translatorProfile = DailyExtracts.select("ted_id, profile_url, name, photo_url, location, profile_languages, for_language, translations, for_date").where(:ted_id => params[:ted_id]).where(:for_language => params[:language]).order("for_date DESC").limit(1).first
		@firstScrapeDate = DailyExtracts.select("for_date").where("for_language = ?", params[:language]).where(:ted_id => params[:ted_id]).order("for_date ASC").first.for_date
		@totalCompletedTasksInLanguage = DailyExtracts.select("SUM(translations) as translations").where("for_language = ?", params[:language]).group("for_date").order('for_date DESC').limit(1).first.translations

		previousForDate = DailyExtracts.select("for_date").where("for_language = ?", params[:language]).where(:ted_id => params[:ted_id]).where("translations != ?", @translatorProfile.translations).order("for_date DESC").limit(1).first
		if previousForDate then
			@lastActiveDate = previousForDate.for_date
		else
			@lastActiveDate = @firstScrapeDate
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OTP Statistics</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body id="<%= controller_name %>-<%= action_name %>">

<%= yield %>

<div id="warning-inaccuracy" class="alert alert-info">
  <h4>Please Note:</h4>
  Since this tool scraped data from TED.com not long ago. Some information might not be 100% accurate (i.e. joining date, last active date). This applies especially to translators who joined before ~20 March 2013, when the first piece of data was scraped. These information will become more accurate over time.
</div>

<% if Rails.env.production? %>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-11150494-14']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
<% end %>

</body>
</html>

app/views/translations/index.html.erb
<% content_for :head do %>
  <%= tag :meta, :name => "index", :content => params[:language] %>
<% end %>

<h1>Statistics for TED Language Coordinators</h1>
<h2>Available languages</h2>

<table>
  <tr>
    <td><h2 class="header-language">Thai</h2></td>
    <td><h2 class="header-language">Swedish</h2></td>
    <td><h2 class="header-language">Dutch</h2></td>
  </tr>
  <tr>
    <td>
      <div id="th" class="graph-wrapper"></div>
      <p class="links-drilldown"><%= link_to("Drill Down", url_for(:action => 'language', :language => "th")) %></p>
    </td>
    <td>
      <div id="sv" class="graph-wrapper"></div>
      <p class="links-drilldown"><%= link_to("Drill Down", url_for(:action => 'language', :language => "sv")) %></p>
    </td>
    <td>
      <div id="nl" class="graph-wrapper"></div>
      <p class="links-drilldown"><%= link_to("Drill Down", url_for(:action => 'language', :language => "nl")) %></p>
    </td>
  </tr>
  <tr>
    <td><h2 class="header-language">Polish</h2></td>
    <td><h2 class="header-language">&nbsp;</h2></td>
    <td><h2 class="header-language">&nbsp;</h2></td>
  </tr>
  <tr>
    <td>
      <div id="pl" class="graph-wrapper"></div>
      <p class="links-drilldown"><%= link_to("Drill Down", url_for(:action => 'language', :language => "pl")) %></p>
    </td>
    <td>
      &nbsp;
    </td>
    <td>
      &nbsp;
    </td>
  </tr>
</table>

app/views/translations/language.html.erb
<% content_for :head do %>
  <%= tag :meta, :name => "language", :content => params[:language] %>
<% end %>

<h1>Statistics for TED Language Coordinators</h1>
<h2>Language: <%= params[:language] %></h2>

<div id="badge-shelf">

  <div class="number-badge-new">
    <h3>New<br />Translators*</h3>
    <p><%= @newTranslators %></p>
  </div>

  <div class="number-badge-new">
    <h3>Active<br />Translators*</h3>
    <p><%= @activeTranslators %></p>
  </div>

  <div class="number-badge-new">
    <h3>New<br />Completed Tasks*</h3>
    <p><%= @newCompletedTasks %></p>
  </div>

  <div class="number-badge">
    <h3>Total<br />Translators</h3>
    <p><%= @totalTranslators.translators %></p>
  </div>

  <div class="number-badge">
    <h3>Total Tasks<br />Compelted</h3>
    <p><%= @totalTasksCompleted.tasks.to_i %></p>
  </div>

  <p class="badge-note">
    * Based on activities within the past 2 weeks
  </p>
</div>

<div id="<%= params[:language] %>" class="graph-wrapper"></div>

<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#firstScraped">First Scraped (New Joiners)</a></li>
  <li><a href="#lastActive">Recently Active</a></li>
  <li><a href="#mostTasks">Most Completed Tasks</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane" id="mostTasks">
    <table class="table table-hover table-striped table-condensed">
      <thead>
        <tr class="tablerow-header">
          <td>#</td>
          <td>Name</td>
          <td>Tasks Completed<br />(Translations + Reviews)</td>
          <td>Location</td>
          <td>First Scrape Date<br />(New joiners?)</td>
          <td>Last Active Date</td>
        </tr>
      </thead>
      <tbody>
        <% @translators.each_with_index do |translator, i| %>
        <tr>
          <td style="text-align: center;"><%= i + 1 %></td>
          <td>
            <%= link_to(translator.name, view_translator_path(:language => params[:language], :ted_id => translator.ted_id)) %> 
            <sup><%= link_to("[TED]", "http://www.ted.com" + translator.profile_url + "/translations", { :class => "tedlink" }) %></sup></td>
          <td style="text-align: center;"><%= translator.translations %></td>
          <td><%= translator.location.presence || '(not available)' %></td>
          <td>
            <%= translator.firstScrapeDate.strftime('%d/%m/%y') %> 
            <% if((Date.today - translator.firstScrapeDate).to_i < 14) then %>
              <span class="time-ago label label-important"><%= time_ago_in_words(translator.firstScrapeDate) %> ago</span>
            <% else %> 
              <span style="color: #aaa; font-size: 8pt;">(<%= time_ago_in_words(translator.firstScrapeDate) %> ago)</span>
            <% end %>
          </td>
          <td>
            <%= translator.lastActiveDate.strftime('%d/%m/%y') %>
            <% if((Date.today - translator.lastActiveDate).to_i < 14) then %>
              <span class="time-ago label label-important"><%= time_ago_in_words(translator.lastActiveDate) %> ago</span>
            <% else %> 
              <span style="color: #aaa; font-size: 8pt;">(<%= time_ago_in_words(translator.lastActiveDate) %> ago)</span>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="tab-pane" id="lastActive">
    <table class="table table-hover table-striped table-condensed">
      <thead>
        <tr class="tablerow-header">
          <td>#</td>
          <td>Name</td>
          <td>Tasks Completed<br />(Translations + Reviews)</td>
          <td>Location</td>
          <td>First Scrape Date<br />(New joiners?)</td>
          <td>Last Active Date</td>
        </tr>
      </thead>
      <tbody>
        <% @translators.sort_by(&:lastActiveDate).reverse.each_with_index do |translator, i| %>
        <tr>
          <td style="text-align: center;"><%= i + 1 %></td>
          <td>
            <%= link_to(translator.name, view_translator_path(:language => params[:language], :ted_id => translator.ted_id)) %> 
            <sup><%= link_to("[TED]", "http://www.ted.com" + translator.profile_url + "/translations", { :class => "tedlink" }) %></sup></td>
          <td style="text-align: center;"><%= translator.translations %></td>
          <td><%= translator.location.presence || '(not available)' %></td>
          <td>
            <%= translator.firstScrapeDate.strftime('%d/%m/%y') %> 
            <% if((Date.today - translator.firstScrapeDate).to_i < 14) then %>
              <span class="time-ago label label-important"><%= time_ago_in_words(translator.firstScrapeDate) %> ago</span>
            <% else %> 
              <span style="color: #aaa; font-size: 8pt;">(<%= time_ago_in_words(translator.firstScrapeDate) %> ago)</span>
            <% end %>
          </td>
          <td>
            <%= translator.lastActiveDate.strftime('%d/%m/%y') %>
            <% if((Date.today - translator.lastActiveDate).to_i < 14) then %>
              <span class="time-ago label label-important"><%= time_ago_in_words(translator.lastActiveDate) %> ago</span>
            <% else %> 
              <span style="color: #aaa; font-size: 8pt;">(<%= time_ago_in_words(translator.lastActiveDate) %> ago)</span>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="tab-pane active" id="firstScraped">
    <table class="table table-hover table-striped table-condensed">
      <thead>
        <tr class="tablerow-header">
          <td>#</td>
          <td>Name</td>
          <td>Tasks Completed<br />(Translations + Reviews)</td>
          <td>Location</td>
          <td>First Scrape Date<br />(New joiners?)</td>
          <td>Last Active Date</td>
        </tr>
      </thead>
      <tbody>
        <% @translators.sort_by(&:firstScrapeDate).reverse.each_with_index do |translator, i| %>
        <tr>
          <td style="text-align: center;"><%= i + 1 %></td>
          <td>
            <%= link_to(translator.name, view_translator_path(:language => params[:language], :ted_id => translator.ted_id)) %> 
            <sup><%= link_to("[TED]", "http://www.ted.com" + translator.profile_url + "/translations", { :class => "tedlink" }) %></sup></td>
          <td style="text-align: center;"><%= translator.translations %></td>
          <td><%= translator.location.presence || '(not available)' %></td>
          <td>
            <%= translator.firstScrapeDate.strftime('%d/%m/%y') %> 
            <% if((Date.today - translator.firstScrapeDate).to_i < 14) then %>
              <span class="time-ago label label-important"><%= time_ago_in_words(translator.firstScrapeDate) %> ago</span>
            <% else %> 
              <span style="color: #aaa; font-size: 8pt;">(<%= time_ago_in_words(translator.firstScrapeDate) %> ago)</span>
            <% end %>
          </td>
          <td>
            <%= translator.lastActiveDate.strftime('%d/%m/%y') %>
            <% if((Date.today - translator.lastActiveDate).to_i < 14) then %>
              <span class="time-ago label label-important"><%= time_ago_in_words(translator.lastActiveDate) %> ago</span>
            <% else %> 
              <span style="color: #aaa; font-size: 8pt;">(<%= time_ago_in_words(translator.lastActiveDate) %> ago)</span>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/translations/translator.html.erb
<% content_for :head do %>
  <%= tag :meta, :name => "language", :content => params[:language] %>
  <%= tag :meta, :name => "ted_id", :content => params[:ted_id] %>
  <%= tag :meta, :name => "last_active_date", :content => @lastActiveDate.strftime('Last task completion on: %e %B %Y') %>  
<% end %>

<h1>Statistics for TED Language Coordinators</h1>
<h2><%= @translatorProfile.name %> (<%= params[:language] %>)</h2>

<div id="badge-shelf">

  <div class="number-badge">
    <h3>Total<br />Tasks Completed</h3>
    <p><%= @translatorProfile.translations %></p>
  </div>

  <div class="number-badge">
    <h3>Percentage of<br /> Language's Tasks</h3>
    <p><%= number_to_percentage(@translatorProfile.translations.to_f / @totalCompletedTasksInLanguage * 100, :precision => 2) %></p>
  </div>

  <div class="number-badge">
    <h3>Last Active Date</h3>
    <p id="how-long-ago"><%= time_ago_in_words(@lastActiveDate) %> ago</p>
  </div>

</div>

<div class="graph-wrapper"></div>